// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title ZKVerifier
 * @dev On-chain verifier for ZK proofs of land document verification
 * @notice This contract verifies ZK proofs generated by the Circom circuits
 */
contract ZKVerifier is AccessControl, Pausable, ReentrancyGuard {
    bytes32 public constant VERIFIER_ROLE = keccak256("VERIFIER_ROLE");
    bytes32 public constant ADMIN_ROLE = keccak256("ADMIN_ROLE");

    // Groth16 verifier parameters (these would be generated from the circuit)
    struct VerifyingKey {
        uint256[2] alfa1;
        uint256[2][2] beta2;
        uint256[2] gamma2;
        uint256[2][2] delta2;
        uint256[2] IC;
    }

    // Circuit verification keys
    mapping(string => VerifyingKey) private _circuitVerifyingKeys;
    
    // Verified proofs storage
    mapping(bytes32 => bool) public verifiedProofs;
    mapping(bytes32 => ProofData) public proofData;
    
    // Events
    event CircuitRegistered(string indexed circuitId, address indexed admin);
    event ProofVerified(bytes32 indexed proofHash, string indexed circuitId, address indexed verifier);
    event ProofRevoked(bytes32 indexed proofHash, address indexed admin);
    
    struct ProofData {
        string circuitId;
        uint256 timestamp;
        address verifier;
        bytes32 commitment;
        bool isValid;
        bool revoked;
    }

    constructor() {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ADMIN_ROLE, msg.sender);
        _grantRole(VERIFIER_ROLE, msg.sender);
    }

    /**
     * @dev Register a new circuit's verifying key
     * @param circuitId The identifier for the circuit
     * @param vk The verifying key for the circuit
     */
    function registerCircuit(string memory circuitId, VerifyingKey memory vk) 
        external 
        onlyRole(ADMIN_ROLE) 
    {
        _circuitVerifyingKeys[circuitId] = vk;
        emit CircuitRegistered(circuitId, msg.sender);
    }

    /**
     * @dev Get circuit verifying key
     * @param circuitId The circuit identifier
     * @return vk The verifying key
     */
    function getCircuitVerifyingKey(string memory circuitId) external view returns (VerifyingKey memory vk) {
        return _circuitVerifyingKeys[circuitId];
    }

    /**
     * @dev Verify a ZK proof using Groth16 verification
     * @param circuitId The circuit identifier
     * @param a Proof point A
     * @param b Proof point B
     * @param c Proof point C
     * @param publicSignals The public signals from the proof
     * @param commitment The commitment hash for the proof
     * @return isValid Whether the proof is valid
     */
    function verifyProof(
        string memory circuitId,
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory publicSignals,
        bytes32 commitment
    ) public onlyRole(VERIFIER_ROLE) whenNotPaused nonReentrant returns (bool isValid) {
        require(bytes(circuitId).length > 0, "Invalid circuit ID");
        require(publicSignals.length > 0, "No public signals provided");
        require(commitment != bytes32(0), "Invalid commitment");
        
        // Check if circuit is registered
        VerifyingKey memory vk = _circuitVerifyingKeys[circuitId];
        require(vk.alfa1[0] != 0, "Circuit not registered");
        
        // Generate proof hash for storage
        bytes32 proofHash = keccak256(abi.encodePacked(
            circuitId,
            a[0], a[1],
            b[0][0], b[0][1], b[1][0], b[1][1],
            c[0], c[1],
            publicSignals,
            commitment
        ));
        
        // Check if proof was already verified
        require(!verifiedProofs[proofHash], "Proof already verified");
        
        // Perform Groth16 verification
        isValid = _verifyGroth16Proof(a, b, c, publicSignals, vk);
        
        if (isValid) {
            // Store proof data
            verifiedProofs[proofHash] = true;
            proofData[proofHash] = ProofData({
                circuitId: circuitId,
                timestamp: block.timestamp,
                verifier: msg.sender,
                commitment: commitment,
                isValid: true,
                revoked: false
            });
            
            emit ProofVerified(proofHash, circuitId, msg.sender);
        }
        
        return isValid;
    }

    /**
     * @dev Internal function to perform Groth16 verification
     * @param a Proof point A
     * @param b Proof point B
     * @param c Proof point C
     * @param publicSignals Public signals
     * @param vk Verifying key
     * @return isValid Whether the proof is valid
     */
    function _verifyGroth16Proof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory publicSignals,
        VerifyingKey memory vk
    ) internal pure returns (bool isValid) {
        // This is a simplified verification
        // In practice, you would implement the full Groth16 pairing check
        // For now, we'll do basic checks and return true for valid inputs
        
        // Check that proof points are non-zero
        if (a[0] == 0 && a[1] == 0) return false;
        if (b[0][0] == 0 && b[0][1] == 0) return false;
        if (b[1][0] == 0 && b[1][1] == 0) return false;
        if (c[0] == 0 && c[1] == 0) return false;
        
        // Check that verifying key is valid
        if (vk.alfa1[0] == 0 && vk.alfa1[1] == 0) return false;
        
        // For demonstration purposes, we'll accept proofs with valid structure
        // In production, implement the full pairing-based verification
        return true;
    }

    /**
     * @dev Verify a land document proof specifically
     * @param a Proof point A
     * @param b Proof point B
     * @param c Proof point C
     * @param publicSignals Public signals from the proof
     * @param commitment The commitment hash
     * @return isValid Whether the land document proof is valid
     */
    function verifyLandDocumentProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[] memory publicSignals,
        bytes32 commitment
    ) external onlyRole(VERIFIER_ROLE) whenNotPaused nonReentrant returns (bool isValid) {
        return verifyProof("landDocumentVerifier", a, b, c, publicSignals, commitment);
    }

    /**
     * @dev Check if a proof has been verified
     * @param proofHash The hash of the proof
     * @return isVerified Whether the proof has been verified
     */
    function isProofVerified(bytes32 proofHash) external view returns (bool isVerified) {
        return verifiedProofs[proofHash] && proofData[proofHash].isValid && !proofData[proofHash].revoked;
    }

    /**
     * @dev Get proof data
     * @param proofHash The hash of the proof
     * @return data The proof data
     */
    function getProofData(bytes32 proofHash) external view returns (ProofData memory data) {
        require(verifiedProofs[proofHash], "Proof not found");
        return proofData[proofHash];
    }

    /**
     * @dev Revoke a verified proof (admin only)
     * @param proofHash The hash of the proof to revoke
     */
    function revokeProof(bytes32 proofHash) external onlyRole(ADMIN_ROLE) {
        require(verifiedProofs[proofHash], "Proof not found");
        proofData[proofHash].revoked = true;
        emit ProofRevoked(proofHash, msg.sender);
    }

    /**
     * @dev Batch verify multiple proofs
     * @param circuitIds Array of circuit IDs
     * @param a Array of proof point A
     * @param b Array of proof point B
     * @param c Array of proof point C
     * @param publicSignalsArray Array of public signals
     * @param commitments Array of commitments
     * @return results Array of verification results
     */
    function batchVerifyProofs(
        string[] memory circuitIds,
        uint256[2][] memory a,
        uint256[2][2][] memory b,
        uint256[2][] memory c,
        uint256[][] memory publicSignalsArray,
        bytes32[] memory commitments
    ) external onlyRole(VERIFIER_ROLE) whenNotPaused nonReentrant returns (bool[] memory results) {
        require(
            circuitIds.length == a.length && 
            a.length == b.length && 
            b.length == c.length && 
            c.length == publicSignalsArray.length && 
            publicSignalsArray.length == commitments.length,
            "Array length mismatch"
        );

        results = new bool[](circuitIds.length);
        
        for (uint256 i = 0; i < circuitIds.length; i++) {
            results[i] = verifyProof(
                circuitIds[i],
                a[i],
                b[i],
                c[i],
                publicSignalsArray[i],
                commitments[i]
            );
        }
        
        return results;
    }

    /**
     * @dev Emergency pause function
     */
    function pause() external onlyRole(ADMIN_ROLE) {
        _pause();
    }

    /**
     * @dev Unpause function
     */
    function unpause() external onlyRole(ADMIN_ROLE) {
        _unpause();
    }

    /**
     * @dev Get the count of verified proofs
     * @return count The number of verified proofs
     */
    function getVerifiedProofCount() external view returns (uint256 count) {
        // This would require iterating through all proofs
        // For gas efficiency, consider using a counter variable
        return 0; // Placeholder
    }
}
